---
name: Build Redbrick Site
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
        name: Install dependencies
      - run: yarn build
        name: Build Site
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SPREADSHEET_ID: "15pFYVzuFPK4HFOpnnFHuoTNh3L3iThBCpoVMQzT5RlM"
          UPTIME_ROBOT_APIKEY: "xxx"
          CI: true
      - name: Package Public Folder
        run: tar -czvf redbrick-site_node-${{ matrix.node-version }}.tar.gz ./public
      - uses: actions/upload-artifact@v2
        with:
          name: Redbrick Site node-${{ matrix.node-version }}
          path: redbrick-site_node-${{ matrix.node-version }}.tar.gz
          retention-days: 5
